services:
  tl-backend-flask:
    build:
      context: .
    image: tl-backend-flask_img
    ports:
      - "7007:7007"
    volumes:
      - ./tl-backend-flask:/home/ubuntu/app/tl-backend-flask
    
    restart: unless-stopped
    
    stdin_open: true
    tty: true
        
    container_name: tl-backend-flask
    hostname: tl-backend-flask